# Tipo de recurso: Define que este YAML é uma configuração de Cluster do Kind
kind: Cluster

# Versão da API: Especifica a versão v1alpha4 da API do Kind (única versão suportada)
apiVersion: kind.x-k8s.io/v1alpha4

# Nome do cluster: Identificador usado em comandos kubectl e docker
name: k8s-essentials

# ========== SEÇÃO DE NODES ==========
nodes:
  # Node 1 - Control Plane (Master)
  # Executa componentes críticos: API Server, Scheduler, Controller Manager, etcd
  - role: control-plane
    
    # Mapeamento de portas extras: Expõe portas do container Docker para o host
    extraPortMappings:
    # Porta 80 → 30080: Para tráfego HTTP (Ingress Controller)
    - containerPort: 8080
      hostPort: 30080

  # Node 2 - Worker: Executa cargas de trabalho (pods de aplicações)
  - role: worker
  
  # Node 3 - Worker: Node adicional para distribuição de carga
  - role: worker