# ============================================================
# ArgoCD Application — Loki
# ============================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    module: "07"
    tier: monitoring

spec:
  project: default

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "*"
      helm:
        releaseName: loki
        valueFiles:
          - $values/curso-k8s/modulo-07-argocd/stack/monitoring/helm-values/values-loki.yaml

    - repoURL: http://gitea-http.gitea.svc.cluster.local:3000/gitops/caio-k8s.git
      # repoURL: https://github.com/SEU_USUARIO/caio-k8s.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
