apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: mario-dev

namePrefix: dev-

labels:
  - pairs:
      env: development

configMapGenerator:
- name: mario-config
  literals:
    - DIFFICULTY=easy
    - WELCOME_MSG="Welcome to Dev Mario"
