apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-mario
  namespace: games
  labels:
    app: super-mario
spec:
  replicas: 2
  selector:
    matchLabels:
      app: super-mario
  template:
    metadata:
      labels:
        app: super-mario
    spec:
      containers:
      - name: super-mario
        image: pengbai/docker-supermario:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
