apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
  namespace: games
  labels:
    app: game-2048
spec:
  type: NodePort
  selector:
    app: game-2048
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  sessionAffinity: None
