apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: mario-prod

namePrefix: prod-

labels:
  - pairs:
      env: production

patches:
  - target:
      kind: Deployment
      name: super-mario
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"

configMapGenerator:
- name: mario-config
  literals:
    - DIFFICULTY=hard
    - WELCOME_MSG="WELCOME TO PRODUCTION - PLAY CAREFULLY"
